# Generated by Django 6.0.2 on 2026-02-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0002_myappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myappointment',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
